package com.liming.workplan.model.pojo;

// Generated 2014-4-27 11:57:44 by Hibernate Tools 4.0.0

/**
 * Attachment generated by hbm2java
 */
public class Attachment implements java.io.Serializable {

	private String attachmentId;
	private String attachmentName;
	private String attachmentURL;
	private String typeDesc;
	private WorkPlanNode workplanNode;

	public Attachment() {
	}

	public Attachment(String attachmentId, WorkPlanNode workplanNode) {
		this.attachmentId = attachmentId;
		this.workplanNode = workplanNode;
	}

	public Attachment(String attachmentId, String attachmentName,
			String attachmentURL, String typeDesc, WorkPlanNode workplanNode) {
		this.attachmentId = attachmentId;
		this.attachmentName = attachmentName;
		this.attachmentURL = attachmentURL;
		this.typeDesc = typeDesc;
		this.workplanNode = workplanNode;
	}

	public String getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(String attachmentId) {
		this.attachmentId = attachmentId;
	}

	public String getAttachmentName() {
		return this.attachmentName;
	}

	public void setAttachmentName(String attachmentName) {
		this.attachmentName = attachmentName;
	}

	public String getAttachmentURL() {
		return this.attachmentURL;
	}

	public void setAttachmentURL(String attachmentURL) {
		this.attachmentURL = attachmentURL;
	}

	public String getTypeDesc() {
		return this.typeDesc;
	}

	public void setTypeDesc(String typeDesc) {
		this.typeDesc = typeDesc;
	}

	public WorkPlanNode getWorkplanNode() {
		return this.workplanNode;
	}

	public void setWorkplanNode(WorkPlanNode workplanNode) {
		this.workplanNode = workplanNode;
	}

}
