package com.liming.workplan.model.pojo;

// Generated 2014-4-20 16:56:40 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ResearchProject generated by hbm2java
 */
public class ResearchProject extends
		com.liming.workplan.model.pojo.WorkPlanNode implements
		java.io.Serializable {

	private String type;
	private String projectType;
	private String projectName;
	private String supportUnit;
	private String projectLevel;
	private String charger;
	private String assistant;
	private double projectFunding;
	private String delegatedDepartment;

	public ResearchProject() {
	}

	public ResearchProject(Attachment attachment, WorkflowNode workflowNode) {
		super(attachment, workflowNode);
	}

	public ResearchProject(long author, Date createDate, String status,
			Attachment attachment, WorkflowNode workflowNode, String type,
			String projectType, String projectName, String supportUnit,
			String projectLevel, String charger, String assistant,
			double projectFunding, String delegatedDepartment) {
		super(author, createDate, status, attachment, workflowNode);
		this.type = type;
		this.projectType = projectType;
		this.projectName = projectName;
		this.supportUnit = supportUnit;
		this.projectLevel = projectLevel;
		this.charger = charger;
		this.assistant = assistant;
		this.projectFunding = projectFunding;
		this.delegatedDepartment = delegatedDepartment;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getProjectType() {
		return this.projectType;
	}

	public void setProjectType(String projectType) {
		this.projectType = projectType;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getSupportUnit() {
		return this.supportUnit;
	}

	public void setSupportUnit(String supportUnit) {
		this.supportUnit = supportUnit;
	}

	public String getProjectLevel() {
		return this.projectLevel;
	}

	public void setProjectLevel(String projectLevel) {
		this.projectLevel = projectLevel;
	}

	public String getCharger() {
		return this.charger;
	}

	public void setCharger(String charger) {
		this.charger = charger;
	}

	public String getAssistant() {
		return this.assistant;
	}

	public void setAssistant(String assistant) {
		this.assistant = assistant;
	}

	public double getProjectFunding() {
		return this.projectFunding;
	}

	public void setProjectFunding(double projectFunding) {
		this.projectFunding = projectFunding;
	}

	public String getDelegatedDepartment() {
		return this.delegatedDepartment;
	}

	public void setDelegatedDepartment(String delegatedDepartment) {
		this.delegatedDepartment = delegatedDepartment;
	}

}
