package com.liming.workplan.model.pojo;

// Generated 2014-4-16 14:57:46 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * WorkflowNode generated by hbm2java
 */
public class WorkflowNode implements java.io.Serializable {

	private int workflowId;
	private Integer hibernateVersion;
	private Integer workplanNodeId;
	private String status;
	private String approver;
	private Date approvedDate;
	private long approvingRoleId;
	private String comment;
	private String nodeType;

	public WorkflowNode() {
	}

	public WorkflowNode(Integer workplanNodeId, String status, String approver,
			Date approvedDate, long approvingRoleId, String comment,
			String nodeType) {
		this.workplanNodeId = workplanNodeId;
		this.status = status;
		this.approver = approver;
		this.approvedDate = approvedDate;
		this.approvingRoleId = approvingRoleId;
		this.comment = comment;
		this.nodeType = nodeType;
	}

	public int getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(int workflowId) {
		this.workflowId = workflowId;
	}

	public Integer getHibernateVersion() {
		return this.hibernateVersion;
	}

	public void setHibernateVersion(Integer hibernateVersion) {
		this.hibernateVersion = hibernateVersion;
	}

	public Integer getWorkplanNodeId() {
		return this.workplanNodeId;
	}

	public void setWorkplanNodeId(Integer workplanNodeId) {
		this.workplanNodeId = workplanNodeId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getApprover() {
		return this.approver;
	}

	public void setApprover(String approver) {
		this.approver = approver;
	}

	public Date getApprovedDate() {
		return this.approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	public long getApprovingRoleId() {
		return this.approvingRoleId;
	}

	public void setApprovingRoleId(long approvingRoleId) {
		this.approvingRoleId = approvingRoleId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getNodeType() {
		return this.nodeType;
	}

	public void setNodeType(String nodeType) {
		this.nodeType = nodeType;
	}

}
