package com.liming.workplan.model.pojo;

// Generated 2014-4-27 11:57:44 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WorkPlanNode generated by hbm2java
 */
public class WorkPlanNode implements java.io.Serializable {

	private int nodeId;
	private long author;
	private Date createDate;
	private String status;
	private WorkflowNode workflowNode;
	private Set attachment = new HashSet(0);

	public WorkPlanNode() {
	}

	public WorkPlanNode(WorkflowNode workflowNode) {
		this.workflowNode = workflowNode;
	}

	public WorkPlanNode(long author, Date createDate, String status,
			WorkflowNode workflowNode, Set attachment) {
		this.author = author;
		this.createDate = createDate;
		this.status = status;
		this.workflowNode = workflowNode;
		this.attachment = attachment;
	}

	public int getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(int nodeId) {
		this.nodeId = nodeId;
	}

	public long getAuthor() {
		return this.author;
	}

	public void setAuthor(long author) {
		this.author = author;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public WorkflowNode getWorkflowNode() {
		return this.workflowNode;
	}

	public void setWorkflowNode(WorkflowNode workflowNode) {
		this.workflowNode = workflowNode;
	}

	public Set getAttachment() {
		return this.attachment;
	}

	public void setAttachment(Set attachment) {
		this.attachment = attachment;
	}

}
